// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// min_run
NumericVector min_run(NumericVector x, IntegerVector k, bool na_pad, bool na_rm, bool na_fill);
RcppExport SEXP _runner_min_run(SEXP xSEXP, SEXP kSEXP, SEXP na_padSEXP, SEXP na_rmSEXP, SEXP na_fillSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type na_pad(na_padSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< bool >::type na_fill(na_fillSEXP);
    rcpp_result_gen = Rcpp::wrap(min_run(x, k, na_pad, na_rm, na_fill));
    return rcpp_result_gen;
END_RCPP
}
// max_run
NumericVector max_run(NumericVector x, IntegerVector k, bool na_pad, bool na_rm, bool na_fill);
RcppExport SEXP _runner_max_run(SEXP xSEXP, SEXP kSEXP, SEXP na_padSEXP, SEXP na_rmSEXP, SEXP na_fillSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type na_pad(na_padSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< bool >::type na_fill(na_fillSEXP);
    rcpp_result_gen = Rcpp::wrap(max_run(x, k, na_pad, na_rm, na_fill));
    return rcpp_result_gen;
END_RCPP
}
// streak_run
IntegerVector streak_run(SEXP x, IntegerVector k, bool na_pad);
RcppExport SEXP _runner_streak_run(SEXP xSEXP, SEXP kSEXP, SEXP na_padSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type na_pad(na_padSEXP);
    rcpp_result_gen = Rcpp::wrap(streak_run(x, k, na_pad));
    return rcpp_result_gen;
END_RCPP
}
// fill_run
SEXP fill_run(SEXP x, bool run_for_first);
RcppExport SEXP _runner_fill_run(SEXP xSEXP, SEXP run_for_firstSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type run_for_first(run_for_firstSEXP);
    rcpp_result_gen = Rcpp::wrap(fill_run(x, run_for_first));
    return rcpp_result_gen;
END_RCPP
}
// mean_run
NumericVector mean_run(NumericVector x, IntegerVector k, bool na_pad, bool na_rm);
RcppExport SEXP _runner_mean_run(SEXP xSEXP, SEXP kSEXP, SEXP na_padSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type na_pad(na_padSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_run(x, k, na_pad, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// sum_run
NumericVector sum_run(NumericVector x, IntegerVector k, bool na_pad, bool na_rm);
RcppExport SEXP _runner_sum_run(SEXP xSEXP, SEXP kSEXP, SEXP na_padSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type na_pad(na_padSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(sum_run(x, k, na_pad, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// whichmax_run
NumericVector whichmax_run(NumericVector vec);
RcppExport SEXP _runner_whichmax_run(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(whichmax_run(vec));
    return rcpp_result_gen;
END_RCPP
}
// whichmin_run
NumericVector whichmin_run(NumericVector vec);
RcppExport SEXP _runner_whichmin_run(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(whichmin_run(vec));
    return rcpp_result_gen;
END_RCPP
}
// whichtrue_run
NumericVector whichtrue_run(LogicalVector vec);
RcppExport SEXP _runner_whichtrue_run(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(whichtrue_run(vec));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_runner_min_run", (DL_FUNC) &_runner_min_run, 5},
    {"_runner_max_run", (DL_FUNC) &_runner_max_run, 5},
    {"_runner_streak_run", (DL_FUNC) &_runner_streak_run, 3},
    {"_runner_fill_run", (DL_FUNC) &_runner_fill_run, 2},
    {"_runner_mean_run", (DL_FUNC) &_runner_mean_run, 4},
    {"_runner_sum_run", (DL_FUNC) &_runner_sum_run, 4},
    {"_runner_whichmax_run", (DL_FUNC) &_runner_whichmax_run, 1},
    {"_runner_whichmin_run", (DL_FUNC) &_runner_whichmin_run, 1},
    {"_runner_whichtrue_run", (DL_FUNC) &_runner_whichtrue_run, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_runner(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
