# commits can contain win, rhub or deploy text for specific actions
name: Check-win-builder
on: push
jobs:

  win-builder-checks:
    runs-on: ubuntu-18.04
    container: rocker/tidyverse:latest
    if: "!contains(github.event.commits[0].message, '[skip other]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send package to win-builder
        shell: Rscript {0}
        run: |
          if (!require("devtools")) install.packages('devtools', repos = 'http://cran.rstudio.com')
          devtools::check_win_devel()
          devtools::check_win_oldrelease()
          devtools::check_win_release()
